---
- hosts: 172.31.23.181
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    register: myfirst
  - name: display my first execution
    debug:
       msg: "{{myfirst}}"
  - name: install git mama
    dnf:
      name: git
      state: present
    when: myfirst.rc== 0
  - name: install tree mama
    dnf: 
      name: tree
      state: present
    when: myfirst.rc!= 0