---
- hosts: 172.31.23.181
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    register: myfirst
  - name: display my first execution
    debug:
       msg: "{{myfirst}}"