---
- hosts: 172.31.23.181
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install git mama
    dnf:
      name: git
      state: present
  - name: copying the file
    copy:
       src: bot file
       dest: /home/somu