---
- hosts: 172.31.23.181
  become: yes
  tasks:
  - name: install git
    dnf:
      name: git
      state: present
  - name: install wget
    dnf:
      name: wget
      state: present
  - name: install tree
    dnf:
      name: tree
      state: present