---
- hosts: 172.31.23.181
  become: yes
  tasks:
  - name: creating files
    file:
      path: /home/somu/myfirstfile
      state: touch
  - name: downloading the internet file
    get_url:
         url: https://adp-mirror-vm1-he-fi.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20-deployer.tar.gz
         dest: /home/somu/apache-tomcat-10.0.20-deployer.tar.gz
         force_basic_auth: yes
  - name: install webserver
    dnf:
      name: httpd  
      state: present
  - name: install webserver
    service:
      name: httpd  
      state: started
  - name: copying
    template: 
          src: waste.j2
          dest: /var/www/html/index.html