---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver
    dnf:
      name: httpd
      state: present
    when: ansible_os_family=="ubuntu"
  - name: start webserver
    service:
      name: httpd
      state: started
    when: ansible_os_family=="ubuntu"