---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver
    dnf:
      name: httpd
      state: present
  - name: start webserver
    service:
      name: httpd
      state: started