---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver
    dnf:
      name: "{{somu}}"
      state: present
    
  - name: start webserver
    service:
      name: "{{somu}}"
      state: started
    