--- 
- name: downloading internet file (tomcat tar)
  get_url:
    url: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/9.0.55/tomcat-9.0.55.tar.gz
    dest: /home/somu/tomcat-9.0.55.tar.gz
    force_basic_auth: yes

- name: creating a new directory
  file:
    path: /opt/tomcat
    state: directory

- name: extract the tar file
  command: 
      cmd: tar -zvxf /home/somu/tomcat-9.0.55.tar.gz -C /opt/tomcat --strip-components=1
      creates: /opt/tomcat/apache-tomcat-9.0.55/LICENSE
