---
- name: update package
  dnf: 
    name: "*"
    state: latest
- name: install java
  dnf: 
    name: java-1.8*
    state: present
- name: install webserver
  dnf: 
    name: httpd
    state: present