---
- name: Ensure /usr/local/bin directory exists
  file:
    path: /usr/local/bin
    state: directory
    

- name: Link tomcatup files
  command: ln -s /home/somu/opt/tomcat/bin/startup.sh /usr/local/bin/tomcatup
  args:
    creates: /usr/local/bin/tomcatup

- name: link tomcatdown files
  command: ln -s /home/somu/opt/tomcat/bin/shutdown.sh usr/local/bin/tomcatdown
  args:
    creates: /usr/local/bin/tomcatup
