---
- name: Ensure symbolic link for tomcatup exists
  file:
    src: /home/somu/opt/tomcat/usr/local/bin/tomcatup
    dest: /usr/local/bin/tomcatup
    state: link

#- name: link tomcatup files
#  command: ln -s /home/somu/opt/tomcat/usr/local/bin/tomcatup
#- name: link tomcatdown files
#  command: ln -s /home/somu/opt/tomcat/usr/local/bin/tomcatdown