--- 
- name: give permissions for startup
  command: chown -R somu:somu /home/somu/opt/tomcat/bin/startup.sh
- name: give permissions for shutdown
  command: chown -R somu:somu /home/somu/opt/tomcat/bin/shutdown.sh
